CREATE TABLE USERS (

ID VARCHAR (450) NOT NULL,
USERNAME VARCHAR(256) NULL,
NORMALIZEDUSERNAME NVARCHAR (256) NULL,
PASSWORDHASH NVARCHAR (256) NULL ,

CONSTRAINT PK_USERS PRIMARY KEY (
ID ASC
));